apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-control-center.fullname" . }}
  labels:
    {{- include "data-control-center.labels" . | nindent 4 }}
data:
  CEPH_DASHBOARD_USERNAME: {{ .Values.config.ceph.api.username | default (randAlphaNum 20) | b64enc }}
  CEPH_DASHBOARD_PASSWORD: {{ .Values.config.ceph.api.password | default (randAlphaNum 40) | b64enc }}
{{- range $k, $v := .Values.additionalEnv }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-control-center.fullname" . }}-config
  labels:
    {{- include "data-control-center.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl (.Values.config | toYaml) . | b64enc }}
