logLevel: 'DEBUG'
# debug or release
mode: 'debug'
http:
  listen: ':8282'
  sessions:
    cookieSecret: 'your_generated_cookie_secret'
    domain: 'localhost'
grpc:
  listen: ':9090'
jwt:
  secret: 'your_generated_jwt_secret'
ceph:
  api:
    url: 'http://localhost:8181/api'
    username: 'admin'
    password: 'admin'
oauth2:
  providers:
    - name: 'keycloak'
      label: 'Keycloak'
      homepage: 'https://keycloak.example.com'
      type: 'generic'
      redirectURL: 'https://localhost:3000/api/oauth2/callback/keycloak'
      clientID: 'your_keycloak_oauth2_client_id'
      clientSecret: 'your_keycloak_oauth2_client_secret'
      scopes:
        - openid
      endpoints:
        authURL: 'https://keycloak.example.com/auth/realms/yourrealm/protocol/openid-connect/auth'
        tokenURL: 'https://keycloak.example.com/auth/realms/yourrealm/protocol/openid-connect/token'
        userInfoURL: 'https://keycloak.example.com/auth/realms/yourrealm/protocol/openid-connect/userinfo'
users: []
