# Please refer to the configuration documentation to learn
# how to setup the config file.
# https://github.com/koor-tech/data-control-center/blob/main/docs/configuration.md#reference
namespace: 'rook-ceph'
logLevel: 'DEBUG'
# debug or release
mode: 'debug'
readOnly: false
http:
  listen: ':8282'
  sessions:
    cookieSecret: 'your_generated_cookie_secret'
    domain: 'localhost'
jwt:
  secret: 'your_generated_jwt_secret'
ceph:
  api:
    url: 'http://localhost:8383/api'
    username: 'admin'
    password: 'admin'
    insecureSSL: false
oauth2:
  providers:
    - name: 'keycloak'
      label: 'Keycloak'
      homepage: 'https://keycloak.example.com'
      type: 'generic'
      redirectURL: 'https://localhost:3000/api/oauth2/callback/keycloak'
      clientID: 'your_keycloak_oauth2_client_id'
      clientSecret: 'your_keycloak_oauth2_client_secret'
      scopes:
        - openid
      endpoints:
        authURL: 'https://keycloak.example.com/auth/realms/yourrealm/protocol/openid-connect/auth'
        tokenURL: 'https://keycloak.example.com/auth/realms/yourrealm/protocol/openid-connect/token'
        userInfoURL: 'https://keycloak.example.com/auth/realms/yourrealm/protocol/openid-connect/userinfo'
users: []
  #- username: 'exampl'
  #  password: 'notagoodpassword123'
updateCheck:
  enabled: true
  interval: 24h
