logLevel: 'DEBUG'
# debug or release
mode: 'debug'
http:
  listen: ':8181'
  sessions:
    cookieSecret: 'your_generated_cookie_secret'
    domain: 'localhost'
grpc:
  listen: ':9191'
jwt:
  secret: 'your_generated_jwt_secret'
oauth2:
  providers:
    - name: 'keycloak'
      label: 'Keycloak'
      homepage: 'https://keycloak.example.com'
      type: 'generic'
      redirectURL: 'https://localhost:3000/api/oauth2/callback/discord'
      clientID: 'your_discord_oauth2_client_id'
      clientSecret: 'your_discord_oauth2_client_secret'
      scopes:
        - openid
        - identify
      endpoints:
        authURL: 'https://keycloak.example.com/api/oauth2/authorize'
        tokenURL: 'https://keycloak.example.com/api/oauth2/token'
