name: Test Code
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  golang-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Run Go Tests
        run: go test ./...

  node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run yarn build
        run: yarn build
