name: Test Code
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  golang-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcephfs-dev librbd-dev librados-dev

      - name: Run Go Tests
        run: go test ./...
